### ISSUE TITLE
关于 amis-editor-sdk

### ISSUE THREAD

**Issue by ayhome** [meixg/amis2schema#5]
老大，我一个做vue后端的，实在弄不懂 react, 找到你的  amis-editor-sdk，跟着 amis-editor-demo-vue做出来了，但是好像版本比较老了， 能不能更新下呢，或者源码可以开放吗？  现在 amis 1.2.2, asmi-editor  3.0.4了，多了不少组件。
最后多谢兄弟的技术付出。

**Comment by meixg** [comment]
amis-editor-sdk 不是我这边维护的
